  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/blog/"

  [[main]]
  name = "Tech Tips"
  weight = 300
  identifier = "techtips"
  url = "/techtips/"

  [[main]]
  name = "Public Talks and Publications"
  weight = 400
  identifier = "public"
  url = "/public/"

  [[main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"