baseURL = "https://kristhecodingunicorn.com"
publishDir = "docs"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Kristina's Tech Corner"
theme = "anatole"
summarylength = 50
enableEmoji = true
enableRobotsTXT = false
# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-RJTQCDFS2Q"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true