baseURL = "https://kristhecodingunicorn.com"
publishDir = "docs"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Kristina's Tech Corner"
theme = "anatole"
summarylength = 50
enableEmoji = true
enableRobotsTXT = false
# Enable Disqus
#disqusShortname = ""

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
