name: Trigger guidemetothemoon content update
on:
  pull_request_target:
    types:
      - closed
    branches: 
      - master
    paths: 
      - 'content/**'
  push:
    branches:
      - master
    paths: 
      - 'content/**'
jobs:
  trigger-guidemetothemoon-workflow:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 1 minute to allow the content to be updated in production
      run: sleep 1m
      shell: bash

    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'guidemetothemoon',
            repo: 'guidemetothemoon',
            workflow_id: 'recent-activities.yml',
            ref: 'main'
          })