name: Run pull request checks
on:
  pull_request:
    paths:
      - 'content/**'
jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # To-Do - alternative approach to perform markdownlint