name: Run pull request checks
on:
    pull_request:
jobs:
    lint-markdown:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: markdownlint-cli2-action
              uses: DavidAnson/markdownlint-cli2-action@v13.0.0
              with:
                globs: 'content/**/*.md'
                config: custom.markdownlint.json
              continue-on-error: true