name: Run pull request checks
on:
  pull_request:
    paths:
      - 'content/**'
jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: tj-actions/changed-files@v39
      id: changed-files
      with:
        files: 'content/**/*.md'
        separator: ","
    
    - name: markdownlint-cli2-action
      uses: DavidAnson/markdownlint-cli2-action@v13.0.0
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
        config: 'custom.markdownlint.jsonc'
      continue-on-error: false